### ISSUE TITLE
When I render, I get an error.

### ISSUE THREAD

**Issue by qixuanwang-233** [liuyuan-pal/SyncDreamer#64]
Hello. When I render, I get the following error.Do you know where the problem is?
(syncdreamer) root@autodl-container-785c4f8ba3-4890e570:~/autodl-tmp/SyncDreamer# python train_renderer.py -i /root/autodl-tmp/SyncDreamer/output/bear/0.png \
>                          -n aircraft-neus \
>                          -b configs/neus.yaml \
>                          -l output/renderer 
Traceback (most recent call last):
  File "/root/autodl-tmp/SyncDreamer/train_renderer.py", line 20, in <module>
    from renderer.renderer import NeuSRenderer, DEFAULT_SIDE_LENGTH
  File "/root/autodl-tmp/SyncDreamer/renderer/renderer.py", line 18, in <module>
    from renderer.neus_networks import SDFNetwork, RenderingNetwork, SingleVarianceNetwork, SDFHashGridNetwork, RenderingFFNetwork
  File "/root/autodl-tmp/SyncDreamer/renderer/neus_networks.py", line 7, in <module>
    import tinycudann as tcnn
  File "/root/miniconda3/envs/syncdreamer/lib/python3.9/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/root/miniconda3/envs/syncdreamer/lib/python3.9/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/root/miniconda3/envs/syncdreamer/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /root/miniconda3/envs/syncdreamer/lib/python3.9/site-packages/tinycudann_bindings/_86_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

**Comment by liuyuan-pal** [comment]
It seems that your tiny-cuda-nn needs to be recompiled. It is not correctly linked.
