### ISSUE TITLE
Is there any docker?

### ISSUE THREAD

**Issue by r530044129** [liuyuan-pal/SyncDreamer#9]
nice work!
do you guys have any docker that we can pull? if have, it will be more convenient!

**Comment by liuyuan-pal** [comment]
Hi! Thanks for the advice. I'll release a docker file for SyncDreamer.

**Comment by liuyuan-pal** [comment]
Hi, the docker is https://hub.docker.com/repository/docker/liuyuanpal/syncdreamer-env/general

**Comment by r530044129** [comment]
thank, i've pull this image, but there is something wrong when i run the python script, please see this cmd log

(base) [root /workspace/apple]$ python generate.py --ckpt ckpt/syncdreamer-pretrain.ckpt \
        >                    --input testset/aircraft.png \
>                    --output output/aircraft \
>                    --sample_num 4 \
>                    --cfg_scale 2.0 \
        >                    --elevation 30 \
>                    --crop_size 200

making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Selected timesteps for ddim sampler: [  1   6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86
  91  96 101 106 111 116 121 126 131 136 141 146 151 156 161 166 171 176
 181 186 191 196 201 206 211 216 221 226 231 236 241 246 251 256 261 266
 271 276 281 286 291 296 301 306 311 316 321 326 331 336 341 346 351 356
 361 366 371 376 381 386 391 396 401 406 411 416 421 426 431 436 441 446
 451 456 461 466 471 476 481 486 491 496 501 506 511 516 521 526 531 536
 541 546 551 556 561 566 571 576 581 586 591 596 601 606 611 616 621 626
 631 636 641 646 651 656 661 666 671 676 681 686 691 696 701 706 711 716
 721 726 731 736 741 746 751 756 761 766 771 776 781 786 791 796 801 806
 811 816 821 826 831 836 841 846 851 856 861 866 871 876 881 886 891 896
 901 906 911 916 921 926 931 936 941 946 951 956 961 966 971 976 981 986
 991 996]
loading model from ckpt/syncdreamer-pretrain.ckpt ...
Traceback (most recent call last):
  File "generate.py", line 61, in <module>
    main()
  File "generate.py", line 40, in main
    model = load_model(flags.cfg, flags.ckpt, strict=True)
  File "generate.py", line 19, in load_model
    model = model.cuda().eval()
  File "/root/miniconda3/lib/python3.8/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 69, in cuda    device = torch.device("cuda", torch.cuda.current_device())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

And I use this cmd to start the docker:
docker run -it --rm  -v /mnt/d/Git/SyncDreamer:/workspace/apple liuyuanpal/syncdreamer-env

Is there any not correct?

**Comment by liuyuan-pal** [comment]
Hi, you need to attach a GPU to the docker instance by `--gpus`.

**Comment by r530044129** [comment]
thanks, I've use this '--gpus all' to start the docker, but it's still has same error, 
torch.cuda.is_available() is false, is there some problem with the cuda version?
![image](https://github.com/liuyuan-pal/SyncDreamer/assets/22882223/944e553a-ef7d-485d-b216-fc46ed9d32da)

**Comment by liuyuan-pal** [comment]
Hi, I'm not sure about the problem. I'm able to load the GPU on my machine.
![image](https://github.com/liuyuan-pal/SyncDreamer/assets/23974453/6c0c632b-f300-4966-8352-fe0970a5ce9b)

Maybe, you could check whether you have GPU in this container by `nvidia-smi`.

**Comment by JunyuanDeng** [comment]
hi, could you please also provide Dockerfile? Thanks a lot!

**Comment by liuyuan-pal** [comment]
Hi, I generate the docker image from a container. I'm not sure about how to generate a docker file from it.

**Comment by JunyuanDeng** [comment]
It doesn't matter, thanks!

**Comment by mshahbazi72** [comment]
Hi

I am trying to use the provided Docker image by pulling it and running a container, but it seems the requirements, including pip, are not installed in the Docker container.

I was wondering if that is the case, or if I am using the Docker incorrectly.

**Comment by liuyuan-pal** [comment]
Hi, it should contain pip and python by default. Maybe, some bugs exist in using docker in your case.

**Comment by Clement-Lelievre** [comment]
> thanks, I've use this '--gpus all' to start the docker, but it's still has same error, torch.cuda.is_available() is false, is there some problem with the cuda version? ![image](https://github.com/liuyuan-pal/SyncDreamer/assets/22882223/944e553a-ef7d-485d-b216-fc46ed9d32da)

same here

<img width="915" height="97" alt="Image" src="https://github.com/user-attachments/assets/a6babda0-f60d-4a85-9ca9-945405bd6014" />
